title: "Understanding Phrases in Context"
description: "PiC: A Dataset for Phrase Understanding and Semantic Search"
theme: jekyll-theme-cayman
# remote_theme: tuur29/pages-themes-cayman

google_analytics: "G-7SWKVJDDB4"
google_analytics_anonymize: false
darkmode: false
show_downloads: true

color:
    gradient_left: "#007A8A"
    gradient_right: "#003D4C"
    header: "#fff"
    android_theme: "#000"     # this default to gradient_color
    link: "#007A8A"           # this default to gradient_color
    section_title: "#003D4C"  # this default to gradient_color

github:
    is_project_page: true
    repository_url: https://github.com/Deehan1866/phrase.github.io
    
buttons:
    zip_url: https://huggingface.co/PiC     # https://auburn.edu/~tmp0038/PiC.zip
    zip_title: Download on Huggingface      # "Download PiC.zip (~196MB)"
    zip_hide: false
    tar_url: https://auburn.edu/~tmp0038/PiC.tar.gz
    tar_title: "Download PiC.tar.gz"
    tar_hide: true
    github_hide: false

# --- List of links in the navigation bar --- #

navbar-links:
    Paper: "https://arxiv.org/abs/2207.09068"
    Demo: "https://prqjasw8k58-496ff2e9c6d22116-5007-colab.googleusercontent.com/"
    Phrase Similarity: "phrase_similarity"
    Phrase Retrieval: "phrase_retrieval"
    Phrase Sense Disambiguation: "phrase_sense_disambiguation"
    #Evaluation: "evaluation"



remove-ads: true

